# Generated by Django 3.1.3 on 2020-11-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_completed',
            field=models.DateField(),
        ),
    ]
