# Generated by Django 3.1.3 on 2020-11-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyrecord_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='noun',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='verb',
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DailyRecord',
        ),
    ]
