# Generated by Django 3.1.3 on 2020-11-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201118_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='noun',
            field=models.CharField(max_length=50),
        ),
    ]
