# Generated by Django 3.1.3 on 2020-11-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201109_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='daily_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('text', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.habit')),
            ],
        ),
    ]
